In [1]:
# Calculate and interpret mean, median, mode, variance and standard deviation for a given dataset.  
#Data =[ 15,21,29,21,15,24,32,21,15,30]

import statistics

data = [15, 21, 29, 21, 15, 24, 32, 21, 15, 30]

# Calculating statistical measures
mean_value = statistics.mean(data)
median_value = statistics.median(data)
mode_value = statistics.mode(data)
variance_value = statistics.variance(data)
std_dev_value = statistics.stdev(data)

# Printing results
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Mode: {mode_value}")
print(f"Variance: {variance_value}")
print(f"Standard Deviation: {std_dev_value}")

Mean: 22.3
Median: 21.0
Mode: 15
Variance: 40.67777777777778
Standard Deviation: 6.377913277693401


In [2]:
#Write a Python program that declares variables of different data types (e.g., string, integer, float, 
#and boolean). Output the variables in a sentence format using print() and f-strings.

name = "Alice"
age = 25
height = 5.6
is_student = True

# Printing results
print(f"My name is {name}, I am {age} years old, my height is {height} feet, and it is {is_student} that I am a student.")


My name is Alice, I am 25 years old, my height is 5.6 feet, and it is True that I am a student.


In [3]:
# Write a Python program that takes an integer input and checks whether the number is positive, 
#negative, or zero using conditional statements (if-else).

# Taking an integer input from the user
num = int(input("Enter an integer: "))

# Checking if the number is positive, negative, or zero
if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")


Enter an integer:  5


The number is positive.


In [4]:
#Write a Python program that takes a number as input and prints the multiplication table 
#for that number (from 1 to 10). 

# Taking a number as input from the user
num = int(input("Enter a number: "))

# Printing multiplication table for the given number
print(f"Multiplication table for {num}:")
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

Enter a number:  5


Multiplication table for 5:
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [5]:
#Create a Python list that contains the names of 5 different fruits. Perform the given operations on 
#the list. 

# Creating a list of 5 different fruits
fruits = ["Apple", "Banana", "Cherry", "Orange", "Grapes"]

# Printing the list of fruits
print("List of fruits:", fruits)

# Adding a new fruit to the list
fruits.append("Mango")
print("After adding Mango:", fruits)

# Removing a fruit from the list
fruits.remove("Cherry")
print("After removing Cherry:", fruits)

# Sorting the list alphabetically
fruits.sort()
print("Sorted list of fruits:", fruits)

# Reversing the list
fruits.reverse()
print("Reversed list of fruits:", fruits)


List of fruits: ['Apple', 'Banana', 'Cherry', 'Orange', 'Grapes']
After adding Mango: ['Apple', 'Banana', 'Cherry', 'Orange', 'Grapes', 'Mango']
After removing Cherry: ['Apple', 'Banana', 'Orange', 'Grapes', 'Mango']
Sorted list of fruits: ['Apple', 'Banana', 'Grapes', 'Mango', 'Orange']
Reversed list of fruits: ['Orange', 'Mango', 'Grapes', 'Banana', 'Apple']


In [6]:
# Write a Python program that creates a tuple containing 5 numbers. Perform the given operations 
#on the tuple. 


# Creating a tuple containing 5 numbers
numbers = (10, 20, 30, 40, 50)

# Printing the tuple
print("Tuple of numbers:", numbers)

# Accessing an element from the tuple
print("Second element:", numbers[1])

# Slicing the tuple
print("First three elements:", numbers[:3])

# Finding the length of the tuple
print("Length of tuple:", len(numbers))

# Finding the sum of elements in the tuple
print("Sum of tuple elements:", sum(numbers))

Tuple of numbers: (10, 20, 30, 40, 50)
Second element: 20
First three elements: (10, 20, 30)
Length of tuple: 5
Sum of tuple elements: 150


In [7]:
#Create a dictionary that stores the names of 3 students as keys and their marks in mathematics as 
#values. Perform the given operations.

# Creating a dictionary with student names as keys and their mathematics marks as values
students_marks = {
    "Alice": 85,
    "Bob": 78,
    "Charlie": 92
}

# Printing the dictionary
print("Student marks in mathematics:", students_marks)

# Accessing marks of a specific student
print("Marks of Alice:", students_marks["Alice"])

# Adding a new student to the dictionary
students_marks["David"] = 88
print("After adding David:", students_marks)

# Updating marks of an existing student
students_marks["Bob"] = 82
print("After updating Bob's marks:", students_marks)

# Removing a student from the dictionary
del students_marks["Charlie"]
print("After removing Charlie:", students_marks)

# Printing all student names
print("List of students:", list(students_marks.keys()))

# Printing all marks
print("List of marks:", list(students_marks.values()))


Student marks in mathematics: {'Alice': 85, 'Bob': 78, 'Charlie': 92}
Marks of Alice: 85
After adding David: {'Alice': 85, 'Bob': 78, 'Charlie': 92, 'David': 88}
After updating Bob's marks: {'Alice': 85, 'Bob': 82, 'Charlie': 92, 'David': 88}
After removing Charlie: {'Alice': 85, 'Bob': 82, 'David': 88}
List of students: ['Alice', 'Bob', 'David']
List of marks: [85, 82, 88]


In [8]:
#Create two sets of integers. Perform the given set operations.

# Creating two sets of integers
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Printing the sets
print("Set 1:", set1)
print("Set 2:", set2)

# Performing set operations
union_set = set1.union(set2)
print("Union of sets:", union_set)

intersection_set = set1.intersection(set2)
print("Intersection of sets:", intersection_set)

set_difference = set1.difference(set2)
print("Difference (Set1 - Set2):", set_difference)

symmetric_difference_set = set1.symmetric_difference(set2)
print("Symmetric Difference of sets:", symmetric_difference_set)


Set 1: {1, 2, 3, 4, 5}
Set 2: {4, 5, 6, 7, 8}
Union of sets: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection of sets: {4, 5}
Difference (Set1 - Set2): {1, 2, 3}
Symmetric Difference of sets: {1, 2, 3, 6, 7, 8}


In [9]:
#Write a Python function called find_largest() that takes a list of numbers as input and returns the 
#largest number from the list. Test the function with a sample list.

# Creating two sets of integers
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Printing the sets
print("Set 1:", set1)
print("Set 2:", set2)

# Performing set operations
union_set = set1.union(set2)
print("Union of sets:", union_set)

intersection_set = set1.intersection(set2)
print("Intersection of sets:", intersection_set)

set_difference = set1.difference(set2)
print("Difference (Set1 - Set2):", set_difference)

symmetric_difference_set = set1.symmetric_difference(set2)
print("Symmetric Difference of sets:", symmetric_difference_set)

# Function to find the largest number in a list
def find_largest(numbers):
    return max(numbers)

# Testing the function with a sample list
sample_list = [10, 25, 37, 4, 89, 56]
largest_number = find_largest(sample_list)
print("The largest number in the list is:", largest_number)


Set 1: {1, 2, 3, 4, 5}
Set 2: {4, 5, 6, 7, 8}
Union of sets: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection of sets: {4, 5}
Difference (Set1 - Set2): {1, 2, 3}
Symmetric Difference of sets: {1, 2, 3, 6, 7, 8}
The largest number in the list is: 89


In [10]:
 #Use list comprehension to create a list of squares of all even numbers between 1 and 20.

# List comprehension to create a list of squares of even numbers between 1 and 20
even_squares = [x**2 for x in range(1, 21) if x % 2 == 0]
print("Squares of even numbers between 1 and 20:", even_squares)


Squares of even numbers between 1 and 20: [4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [11]:
#Write a Python script that uses a lambda function to calculate the product of two numbers provided 
#by the user.

# Lambda function to calculate the product of two numbers
product = lambda x, y: x * y

# Taking user input
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

# Calculating and printing the product
print(f"The product of {num1} and {num2} is: {product(num1, num2)}")

Enter the first number:  5
Enter the second number:  6


The product of 5 and 6 is: 30


In [12]:
#Write a Python program to create a one-dimensional, two-dimensional, and three-dimensional 
#NumPy array. Print the shape and dimensions of each array.

import numpy as np

# Creating a one-dimensional NumPy array
one_d_array = np.array([1, 2, 3, 4, 5])
print("One-Dimensional Array:", one_d_array)
print("Shape:", one_d_array.shape)
print("Dimensions:", one_d_array.ndim)

# Creating a two-dimensional NumPy array
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print("\nTwo-Dimensional Array:\n", two_d_array)
print("Shape:", two_d_array.shape)
print("Dimensions:", two_d_array.ndim)

# Creating a three-dimensional NumPy array
three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nThree-Dimensional Array:\n", three_d_array)
print("Shape:", three_d_array.shape)
print("Dimensions:", three_d_array.ndim)


One-Dimensional Array: [1 2 3 4 5]
Shape: (5,)
Dimensions: 1

Two-Dimensional Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2

Three-Dimensional Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3


In [14]:
#Write a Python program to create a 5x5 NumPy array of random integers and Perform array 
#indexing as given.

import numpy as np

# Creating a 5x5 NumPy array of random integers between 1 and 100
random_array = np.random.randint(1, 101, (5, 5))
print("5x5 Random Integer Array:\n", random_array)

# Performing array indexing
print("\nElement at row 2, column 3:", random_array[1, 2])
print("First row:", random_array[0, :])
print("Last column:", random_array[:, -1])
print("Subarray (first 3 rows, first 3 columns):\n", random_array[:3, :3])


5x5 Random Integer Array:
 [[44 41 14 31 26]
 [35 70 57 85 45]
 [92 34 23 94  5]
 [32 11 90 43 48]
 [39 68  1  3 88]]

Element at row 2, column 3: 57
First row: [44 41 14 31 26]
Last column: [26 45  5 48 88]
Subarray (first 3 rows, first 3 columns):
 [[44 41 14]
 [35 70 57]
 [92 34 23]]


In [15]:
#create a NumPy array of shape (4, 4) containing numbers from 1 to 16. Use slicing to extract for 
#the given conditions 

import numpy as np

# Creating a 4x4 NumPy array containing numbers from 1 to 16
array_4x4 = np.arange(1, 17).reshape(4, 4)
print("4x4 NumPy Array:\n", array_4x4)

# Performing slicing operations
print("\nFirst two rows:\n", array_4x4[:2, :])
print("Last two columns:\n", array_4x4[:, -2:])
print("Subarray (middle 2x2 block):\n", array_4x4[1:3, 1:3])
print("Diagonal elements:", array_4x4.diagonal())

4x4 NumPy Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First two rows:
 [[1 2 3 4]
 [5 6 7 8]]
Last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
Subarray (middle 2x2 block):
 [[ 6  7]
 [10 11]]
Diagonal elements: [ 1  6 11 16]


In [16]:
#Write a Python program that creates a 2D array of shape (6, 2) using np.arange() and then reshapes 
#it into a 3D array of shape (2, 3, 2). Flatten the reshaped array and print the result. 

import numpy as np

# Creating a 2D array of shape (6, 2) using np.arange()
array_2d = np.arange(1, 13).reshape(6, 2)
print("2D Array (6x2):\n", array_2d)

# Reshaping the array into a 3D array of shape (2, 3, 2)
array_3d = array_2d.reshape(2, 3, 2)
print("\nReshaped 3D Array (2x3x2):\n", array_3d)

# Flattening the reshaped array
flattened_array = array_3d.flatten()
print("\nFlattened Array:", flattened_array)

2D Array (6x2):
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Reshaped 3D Array (2x3x2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
#Write a Python program to demonstrate broadcasting. Create an array of shape (3, 3) and add a one
#dimensional array of shape (1, 3) to it using broadcasting.

import numpy as np

# Creating a 3x3 array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original 3x3 Array:\n", array_2d)

# Creating a 1D array of shape (1, 3)
array_1d = np.array([10, 20, 30])
print("\n1D Array:\n", array_1d)

# Using broadcasting to add the 1D array to the 3x3 array
broadcasted_result = array_2d + array_1d
print("\nResult after Broadcasting:\n", broadcasted_result)


Original 3x3 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

1D Array:
 [10 20 30]

Result after Broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [18]:
#Create two NumPy arrays of the same shape, A and B. Perform the following arithmetic operations: 
#Element-wise addition. 
#Element-wise subtraction. 
#Element-wise multiplication. 
#Element-wise division
import numpy as np

# Creating two NumPy arrays of the same shape
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("Array A:\n", A)
print("\nArray B:\n", B)

# Performing arithmetic operations
addition_result = A + B
print("\nElement-wise Addition:\n", addition_result)

subtraction_result = A - B
print("\nElement-wise Subtraction:\n", subtraction_result)

multiplication_result = A * B
print("\nElement-wise Multiplication:\n", multiplication_result)

division_result = A / B
print("\nElement-wise Division:\n", division_result)



Array A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Element-wise Division:
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [1]:
#Create a Pandas DataFrame with the given Name and marks of 3 courses: 
#Add a new column named 'Total' that represents the sum of all the courses. Add 'Grade' based 
#on the values of the 'Total'. Print the updated DataFrame with the new 'Total' and 'Grade' 
#column. 

import pandas as pd

# Creating a DataFrame with student names and marks
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma'],
    'Math': [85, 78, 92, 60, 89],
    'Science': [90, 82, 88, 75, 95],
    'English': [88, 76, 80, 70, 90]
}
df = pd.DataFrame(data)

# Adding 'Total' column
df['Total'] = df[['Math', 'Science', 'English']].sum(axis=1)

# Function to determine grade
def assign_grade(total):
    if total >= 270:
        return 'A'
    elif total >= 240:
        return 'B'
    elif total >= 210:
        return 'C'
    elif total >= 180:
        return 'D'
    else:
        return 'F'

# Adding 'Grade' column
df['Grade'] = df['Total'].apply(assign_grade)

# Printing the updated DataFrame
print(df)


      Name  Math  Science  English  Total Grade
0    Alice    85       90       88    263     B
1      Bob    78       82       76    236     C
2  Charlie    92       88       80    260     B
3    David    60       75       70    205     D
4     Emma    89       95       90    274     A
